"""Add score to Skill and is_archived to Student

Revision ID: e0362d908a72
Revises: 36edfb7dfe52
Create Date: 2026-02-02 09:01:45.210558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0362d908a72'
down_revision: Union[str, Sequence[str], None] = '36edfb7dfe52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_archived')
    op.drop_column('skills', 'score')
    # ### end Alembic commands ###
